// src/constants/index.tsx

export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CMD_BUTTON_CLICK = 'CMD_BUTTON_CLICK';
export type CMD_BUTTON_CLICK = typeof CMD_BUTTON_CLICK;

export const CELL_CLICK = 'CELL_CLICK';
export type CELL_CLICK = typeof CELL_CLICK;

export const CELL_SETVALUE = 'CELL_SETVALUE';
export type CELL_SETVALUE = typeof CELL_SETVALUE;

export const CLICK_NUM_BUTTON = 'CLICK_NUM_BUTTON';
export type CLICK_NUM_BUTTON = typeof CLICK_NUM_BUTTON;